name: example
version: 1.0.0
description: Charts-Flutter Demo
publish_to: 'none'
environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  charts_flutter:
    path: ../
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: ^1.9.1
  intl: ^0.18.0

flutter:
  uses-material-design: true
